CREATE TABLE CLIENTS (
    CLN_ID NUMBER PRIMARY KEY,
    CLN_NAME VARCHAR2 (200 BYTE),
    CLN_LNAME_1 VARCHAR2 (200 BYTE),
    CLN_LNAME_2 VARCHAR2 (200 BYTE),
    CLN_RFC VARCHAR2 (200 BYTE),
    CLN_FISC_ZIP_CODE VARCHAR2(200 BYTE),
    CLN_EMAIL VARCHAR2 (200 BYTE),
    CFDI_USE VARCHAR2(10 BYTE),
    CLN_STATUS VARCHAR2 (200 BYTE)
)